version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env

  mongo:
    image: mongo:4
    container_name: mongo_db_infotec
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


